part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const Home = _Paths.home;
  static const LOGIN = _Paths.LOGIN;
  static const Otp = _Paths.OTP;
  static const ADD = _Paths.ADD;
  static const HELP_CENTER = _Paths.HELP_CENTER;
  static const text_support = _Paths.text_support;
  static const ticket = _Paths.ticket;
  static const video_tutorial = _Paths.videotutorial;
  static const faq = _Paths.faq;
  static const faq_grid_pages = _Paths.faq_grid_pages;
  static const REGISTRATION = _Paths.REGISTRATION;
  static const store_details = _Paths.store_details;
  static const store_select_module = _Paths.store_select_module;
  static const store_category = _Paths.store_category;
  static const Store_details_form = _Paths.store_details_form;
  static const store_template = _Paths.store_template;
  static const store_location = _Paths.store_location;
  static const store_location_search = _Paths.store_location_search;
  static const KYC_DOCUMENTS = _Paths.KYC_DOCUMENTS;
  static const select_document = _Paths.select_document;
  static const kyc_upload_document = _Paths.kyc_upload_document;
  static const business_kyc = _Paths.business_kyc;
  static const BANK_DETAILS = _Paths.BANK_DETAILS;
  static const upi_details = _Paths.upi_details;
  static const bank_details_form = _Paths.bank_details_form;
  static const thankyou_page = _Paths.thankyou_page;
  static const HomeBottomBarView = _Paths.HomeBottomBarView;
  static const STORE_PROFILE = _Paths.STORE_PROFILE;
  static const StoresprofileView = _Paths.StoresprofileView;
  static const ReviewView = _Paths.ReviewView;
  static const AboutView = _Paths.AboutView;
  static const OWNER_PROFILE = _Paths.OWNER_PROFILE;
  static const POS = _Paths.POS;
  static const Pos_category = _Paths.Pos_category;
  static const pos_category_search_view = _Paths.pos_category_search_view;
  static const pos_Search_Result_view = _Paths.pos_Search_Result_view;
  static const Checkout = _Paths.checkout;
  static const INVENTORY = _Paths.INVENTORY;
  static const INVENTRY = _Paths.INVENTRY;
  static const WALLET = _Paths.WALLET;
  static const KHATA_BOOK = _Paths.KHATA_BOOK;
  static const ADD_COUPONS = _Paths.ADD_COUPONS;
  static const ADVERTISEMENT = _Paths.ADVERTISEMENT;
  static const SPLASH_PAGE = _Paths.SPLASH_PAGE;
}

abstract class _Paths {
  static const home = '/home';
  static const LOGIN = '/login';
  static const OTP = '/otp';
  static const ADD = '/add';
  static const HELP_CENTER = '/help-center';
  static const text_support = '/text-support';
  static const ticket = '/ticket';
  static const videotutorial = '/videotutorial';
  static const faq = '/faq';
  static const faq_grid_pages = '/faq_grid_pages';
  static const REGISTRATION = '/registration';
  static const store_details = '/store-details';
  static const store_select_module = '/store_select_module';
  static const store_category = '/store_category';
  static const store_details_form = '/store_details_form';
  static const store_template = '/store_template';
  static const store_location = '/store_location';
  static const store_location_search = '/store_location_search';
  static const KYC_DOCUMENTS = '/kyc-documents';
  static const select_document = '/select_document';
  static const kyc_upload_document = '/kyc_upload_document';
  static const business_kyc = '/business_kyc';
  static const BANK_DETAILS = '/bank-details';
  static const upi_details = '/upi_details';
  static const bank_details_form = '/bank_details_form';
  static const thankyou_page = '/thankyou_page';
  static const HomeBottomBarView = '/homeBottomBarView';
  static const STORE_PROFILE = '/store-profile';
  static const StoresprofileView = '/storesprofileView';
  static const ReviewView = '/reviewView';
  static const AboutView = '/aboutView';
  static const OWNER_PROFILE = '/owner-profile';
  static const POS = '/pos';
  static const Pos_category = '/pos_category';
  static const pos_category_search_view = '/pos_category_search_view';
  static const pos_Search_Result_view = '/pos_Search_Result_view';
  static const checkout = '/checkout';
  static const INVENTORY = '/inventory';
  static const INVENTRY = '/inventry';
  static const WALLET = '/wallet';
  static const KHATA_BOOK = '/khata-book';
  static const ADD_COUPONS = '/add-coupons';
  static const ADVERTISEMENT = '/advertisement';
  static const SPLASH_PAGE = '/splash-page';
}
